# Cleaner Makefile

CLEAN = rm -rf db simulation *.bak output_files incremental_db *.rpt *.qws

toplevel:
	echo "Not yet"

alu_modules:
	cd datapath/modules/alu/modules && $(CLEAN)

all: toplevel alu_modules
